/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCCompanyRouteImport } from './routes/_authenticated/c.$company'
import { Route as AuthenticatedHistorialIndexRouteImport } from './routes/_authenticated/historial.index'
import { Route as AuthenticatedHistorialSnapshotIdRouteImport } from './routes/_authenticated/historial.$snapshotId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCCompanyRoute = AuthenticatedCCompanyRouteImport.update({
  id: '/c/$company',
  path: '/c/$company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialIndexRoute =
  AuthenticatedHistorialIndexRouteImport.update({
    id: '/historial/',
    path: '/historial/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistorialSnapshotIdRoute =
  AuthenticatedHistorialSnapshotIdRouteImport.update({
    id: '/historial/$snapshotId',
    path: '/historial/$snapshotId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/c/$company': typeof AuthenticatedCCompanyRoute
  '/historial/$snapshotId': typeof AuthenticatedHistorialSnapshotIdRoute
  '/historial/': typeof AuthenticatedHistorialIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/c/$company': typeof AuthenticatedCCompanyRoute
  '/historial/$snapshotId': typeof AuthenticatedHistorialSnapshotIdRoute
  '/historial': typeof AuthenticatedHistorialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/c/$company': typeof AuthenticatedCCompanyRoute
  '/_authenticated/historial/$snapshotId': typeof AuthenticatedHistorialSnapshotIdRoute
  '/_authenticated/historial/': typeof AuthenticatedHistorialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/c/$company' | '/historial/$snapshotId' | '/historial/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/c/$company' | '/historial/$snapshotId' | '/historial'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/c/$company'
    | '/_authenticated/historial/$snapshotId'
    | '/_authenticated/historial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$company': {
      id: '/_authenticated/c/$company'
      path: '/c/$company'
      fullPath: '/c/$company'
      preLoaderRoute: typeof AuthenticatedCCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial/': {
      id: '/_authenticated/historial/'
      path: '/historial'
      fullPath: '/historial/'
      preLoaderRoute: typeof AuthenticatedHistorialIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial/$snapshotId': {
      id: '/_authenticated/historial/$snapshotId'
      path: '/historial/$snapshotId'
      fullPath: '/historial/$snapshotId'
      preLoaderRoute: typeof AuthenticatedHistorialSnapshotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCCompanyRoute: typeof AuthenticatedCCompanyRoute
  AuthenticatedHistorialSnapshotIdRoute: typeof AuthenticatedHistorialSnapshotIdRoute
  AuthenticatedHistorialIndexRoute: typeof AuthenticatedHistorialIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCCompanyRoute: AuthenticatedCCompanyRoute,
  AuthenticatedHistorialSnapshotIdRoute: AuthenticatedHistorialSnapshotIdRoute,
  AuthenticatedHistorialIndexRoute: AuthenticatedHistorialIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
